name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer install

      - name: Test MySQL connection
        run: |
          mysql -h sql7.freemysqlhosting.net -u sql7740449 -p8KpMy7sQSq -e 'SHOW DATABASES;'

      - name: Wait for MySQL to be ready
        run: |
          until mysql -h sql7.freemysqlhosting.net -u sql7740449 -p8KpMy7sQSq -e 'SELECT 1'; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Run migrations
        run: |
          php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run tests
        run: |
          php bin/phpunit
