name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Cache Symfony binary
        uses: actions/cache@v3
        with:
          path: .symfony/bin
          key: ${{ runner.os }}-symfony-${{ hashFiles('**/composer.lock') }}

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  
        run: php bin/phpunit
