name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'
          extensions: mbstring, intl, pdo_mysql

      - name: Install dependencies
        run: composer install

      - name: Verify vendor/bin/phpunit exists
        run: ls -l vendor/bin/phpunit

      - name: Wait for MySQL to be ready
        run: |
          until mysql -h127.0.0.1 -uroot -proot -e "SELECT 1"; do
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: php vendor/bin/phpunit
